### ISSUE TITLE
Error when using mysql2 gem (as well as pg).

### ISSUE THREAD

**Issue by fourseven** [dockyard/postgres_ext#152]
We've got two database sources in our app, our primary is a RDS Postgres instance, and we also have a migration database which is a dump from another app which is on mysql and has user data which we are migrating into postgres/our app (two ActiveRecord::Base connections, essentially). Since upgrading postgres_ext `WHERE IN` queries through mysql are failing due to:

```
NoMethodError: undefined method `array' for #<ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::Column:0x007fe740898210>
from /Users/mathew/.gem/ruby/2.1.5/gems/postgres_ext-2.4.0.beta.1/lib/postgres_ext/active_record/relation/predicate_builder.rb:12:in `build'
```

I can submit a pull request but for the life of me I'm not sure how to create a test case for this, so suggestions are welcome!

**Comment by edpaget** [comment]
Closed by #153
