### ISSUE TITLE
CTEs not working with squeel gem

### ISSUE THREAD

**Issue by sebastianvera** [dockyard/postgres_ext#158]
I'm using Rails 4.2.0, postgres_ext-2.4.1, squeel-1.2.3 and ruby 2.2.0.

### from_cte

When I use `Bar.from_cte('foo', Bar.where(created_at: Date.current.all_month))` it simply returns `#<ActiveRecord::Relation:0x3fd308fc40ac>`, but if I call a method on it, it throws ```NoMethodError: undefined method `arel_engine' for #<CTEProxy:0x007fa6159aa4f8> from path/to/squeel-1.2.3/lib/squeel/adapters/active_record/4.1/context.rb:12:in `initialize'```

This is the `context.rb` file:

```ruby
# squeel-1.2.3/lib/squeel/adapters/active_record/4.1/context.rb
module Squeel
  module Adapters
    module ActiveRecord
      class Context < ::Squeel::Context
        class NoParentFoundError < RuntimeError; end

        def initialize(object)
          super
          @base = object.join_root
          @engine = @base.base_klass.arel_engine # this is the conflicting line
          @arel_visitor = get_arel_visitor
          @default_table = Arel::Table.new(@base.table_name, :as => @base.aliased_table_name, :engine => @engine)
        end
...
```

I tried fixing this error by changing `@engine = @base.base_klass.arel_engine` to `@engine = @base.base_klass.arel_table.engine`.

```ruby
# squeel-1.2.3/lib/squeel/adapters/active_record/4.1/context.rb
module Squeel
  module Adapters
    module ActiveRecord
      class Context < ::Squeel::Context
        class NoParentFoundError < RuntimeError; end

        def initialize(object)
          super
          @base = object.join_root
          @engine = @base.base_klass.arel_table.engine # modified line
          @arel_visitor = get_arel_visitor
          @default_table = Arel::Table.new(@base.table_name, :as => @base.aliased_table_name, :engine => @engine)
        end
...
```

This prevents the error, but behaves as if `from_cte` was never called, returning wrong results.

### with

When I use `Bar.with(foo: Bar.where(created_at: Date.current.all_month)).joins("JOIN foo ON foo.id = bars.id")` it returns `PG::UndefinedTable: ERROR:  relation "foo" does not exist`. 

-----

If I remove the squeel gem, both `from_cte` and `with` works great.

Should I create an issue in the squeel gem also? Or is a postgres_ext problem?

**Comment by bcardarella** [comment]
I'l leave it up to @danmcclain but my 2 cents is that we shouldn't support squeel. It is doing so much crazy stuff under the hood and Ernie has a tendency of abandoning versions of this library.

**Comment by danmcclain** [comment]
I don't think it makes sense to make postgres_ext to support squeel, postgres_ext makes extensive use of arel, and squeel mucks around with arel too much. It would be hard to stay compatible with both arel then squeel. Squeel and postgres_ext will continue to step on each others' toes. Sorry
