### ISSUE TITLE
Feature: Support for "where.exists"

### ISSUE THREAD

**Issue by svoop** [dockyard/postgres_ext#175]
EXISTS subqueries are not currently supported by AR, but often a faster and more readable alternative to IN or INNER JOIN.

Here's a simple yet nonsensical example. Up until AR 4.1, the following worked:

    # AR 4.1.13
    Post.where(Comment.where(id: 123).exists).to_sql
    => SELECT "posts".* FROM "posts" WHERE (EXISTS (SELECT "comments".* FROM "comments" WHERE "comments"."id" = 123))

However, since `exists` is not part of the public API, it no longer works on AR 4.2. [There's a discussion](https://github.com/rails/rails/issues/16959) to support `where.exists` in the future of AR, the code would look as follows:

    Post.where.exists(Comment.where(id: 123))

Until then, a workaround is the [where_exists gem](https://github.com/eugzol/where_exists). While it works on different backends, it's another dependency in the Gemfile. The syntax is different and it is less flexible because it only works for associated models:

    Post.where_exists(:comments, id: 123)

Also the gem only works for associated models and therefore is less flexible. It's useless e.g. for this scope which does a little PostGIS hocus pocus where `Area` is not associated to `Location`(the model on which the scope is defined):

    scope :inside, ->(area_id) { where(Area.where(id: area_id).where.exists("ST_Intersects(locations.geography, geography)")) }

How about adding support for `where.exists` to postgres_ext until AR comes forward with something similar? IMO, it would be a nice fit along with the other extensions such as `where.all`.

**Comment by edpaget** [comment]
It seems like `where.exists` might make more sense in a separate gem. Our `any` and `all` methods are needed for Postgresql's arrays, but `where.exists` appears to be usable in several database, so I'm not sure we should include it in this gem. 

That said, I would definitely look at a patch if you or someone else has time to put one together.

**Comment by svoop** [comment]
I tend to agree. In fact, EXISTS are useful enough to become part of the AR core, however, looking at the history of `or`, I'm not so optimistic this will happen any time soon.
